name: .NET Core Test

on: pull_request

env:
  DOTNET_VERSION: 3.0.100

jobs:

  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Chectout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Check format
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet tool install --tool-path ./ dotnet-format
        ./dotnet-format --check --dry-run -v diagnostic
    - name: Test neo-cli
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libleveldb-dev expect
        dotnet publish -o ./out -c Release neo-cli
        expect ./.github/workflows/test-neo-cli.expect
        ./.github/workflows/rpc-tests.sh
    - name: Test neo-gui
      if: matrix.os == 'windows-latest'
      run: dotnet build -c Release neo-gui
